# Generated by Django 4.0.4 on 2022-07-04 07:34

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertsement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('body', ckeditor_uploader.fields.RichTextUploadingField()),
                ('category', models.CharField(choices=[('TN', 'Танк'), ('HL', 'Хил'), ('DD', 'ДД'), ('VN', 'Торговец'), ('GM', 'Гильдмастер'), ('QG', 'Квестгивер'), ('BS', 'Кузнец'), ('TR', 'Кожевенник'), ('PM', 'Зельевар'), ('SM', 'Мастер заклинаний'), ('OR', 'Другое')], default='OR', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Replies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('advertsement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='message_boards.advertsement')),
            ],
        ),
    ]
